# Generated by Django 5.0.2 on 2024-03-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
